--1.The total revenue generated by male vs. female customers
select gender, SUM(purchase_amount) as revenue 
from customer group by gender

--2.customers used a discount but still spent more than the average purchase amount
select customer_id,purchase_amount from customer
where discount_applied='Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--3.The top 5 products with the highest average review rating
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

 
--Q9.Customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--10. What is the revenue contribution of each age group 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;